//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionComptesRendus
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSTITUER
    {
        public string MED_DEPOTLEGAL { get; set; }
        public string CMP_CODE { get; set; }
        public Nullable<float> CST_QTE { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual COMPOSANT COMPOSANT { get; set; }
        public virtual MEDICAMENT MEDICAMENT { get; set; }
    }
}
