//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionComptesRendus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionComptesRendusEntities : DbContext
    {
        public GestionComptesRendusEntities()
            : base("name=GestionComptesRendusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVITE_COMPL> ACTIVITE_COMPL { get; set; }
        public virtual DbSet<COMPOSANT> COMPOSANT { get; set; }
        public virtual DbSet<CONSTITUER> CONSTITUER { get; set; }
        public virtual DbSet<DOSAGE> DOSAGE { get; set; }
        public virtual DbSet<FAMILLE> FAMILLE { get; set; }
        public virtual DbSet<INVITER> INVITER { get; set; }
        public virtual DbSet<LABO> LABO { get; set; }
        public virtual DbSet<MEDICAMENT> MEDICAMENT { get; set; }
        public virtual DbSet<OFFRIR> OFFRIR { get; set; }
        public virtual DbSet<POSSEDER> POSSEDER { get; set; }
        public virtual DbSet<PRATICIEN> PRATICIEN { get; set; }
        public virtual DbSet<PRESCRIRE> PRESCRIRE { get; set; }
        public virtual DbSet<PRESENTATION> PRESENTATION { get; set; }
        public virtual DbSet<RAPPORT_VISITE> RAPPORT_VISITE { get; set; }
        public virtual DbSet<REALISER> REALISER { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<SECTEUR> SECTEUR { get; set; }
        public virtual DbSet<SPECIALITE> SPECIALITE { get; set; }
        public virtual DbSet<Switchboard_Items> Switchboard_Items { get; set; }
        public virtual DbSet<TRAVAILLER> TRAVAILLER { get; set; }
        public virtual DbSet<TYPE_INDIVIDU> TYPE_INDIVIDU { get; set; }
        public virtual DbSet<TYPE_PRATICIEN> TYPE_PRATICIEN { get; set; }
        public virtual DbSet<VISITEUR> VISITEUR { get; set; }
    }
}
