//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionComptesRendus
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOSAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOSAGE()
        {
            this.PRESCRIRE = new HashSet<PRESCRIRE>();
        }
    
        public string DOS_CODE { get; set; }
        public string DOS_QUANTITE { get; set; }
        public string DOS_UNITE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESCRIRE> PRESCRIRE { get; set; }
    }
}
