//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionComptesRendus
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVITER
    {
        public int AC_NUM { get; set; }
        public short PRA_NUM { get; set; }
        public Nullable<bool> SPECIALISTEON { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual ACTIVITE_COMPL ACTIVITE_COMPL { get; set; }
        public virtual PRATICIEN PRATICIEN { get; set; }
    }
}
