//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionComptesRendus
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRATICIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRATICIEN()
        {
            this.INVITER = new HashSet<INVITER>();
            this.POSSEDER = new HashSet<POSSEDER>();
            this.RAPPORT_VISITE = new HashSet<RAPPORT_VISITE>();
        }
    
        public short PRA_NUM { get; set; }
        public string PRA_NOM { get; set; }
        public string PRA_PRENOM { get; set; }
        public string PRA_ADRESSE { get; set; }
        public string PRA_CP { get; set; }
        public string PRA_VILLE { get; set; }
        public Nullable<float> PRA_COEFNOTORIETE { get; set; }
        public string TYP_CODE { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVITER> INVITER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSSEDER> POSSEDER { get; set; }
        public virtual TYPE_PRATICIEN TYPE_PRATICIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAPPORT_VISITE> RAPPORT_VISITE { get; set; }
    }
}
