//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionComptesRendus
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESCRIRE
    {
        public string MED_DEPOTLEGAL { get; set; }
        public string TIN_CODE { get; set; }
        public string DOS_CODE { get; set; }
        public string PRE_POSOLOGIE { get; set; }
    
        public virtual DOSAGE DOSAGE { get; set; }
        public virtual MEDICAMENT MEDICAMENT { get; set; }
        public virtual TYPE_INDIVIDU TYPE_INDIVIDU { get; set; }
    }
}
