//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionComptesRendus
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAPPORT_VISITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAPPORT_VISITE()
        {
            this.OFFRIR = new HashSet<OFFRIR>();
        }
    
        public string VIS_MATRICULE { get; set; }
        public int RAP_NUM { get; set; }
        public short PRA_NUM { get; set; }
        public Nullable<System.DateTime> RAP_DATE { get; set; }
        public string RAP_BILAN { get; set; }
        public string RAP_MOTIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFRIR> OFFRIR { get; set; }
        public virtual PRATICIEN PRATICIEN { get; set; }
        public virtual VISITEUR VISITEUR { get; set; }
    }
}
