//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionComptesRendus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Switchboard_Items
    {
        public int SwitchboardID { get; set; }
        public short ItemNumber { get; set; }
        public string ItemText { get; set; }
        public Nullable<short> Command { get; set; }
        public string Argument { get; set; }
    }
}
