//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionComptesRendus
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VISITEUR()
        {
            this.RAPPORT_VISITE = new HashSet<RAPPORT_VISITE>();
            this.REALISER = new HashSet<REALISER>();
            this.TRAVAILLER = new HashSet<TRAVAILLER>();
        }
    
        public string VIS_MATRICULE { get; set; }
        public string VIS_NOM { get; set; }
        public string Vis_PRENOM { get; set; }
        public string VIS_ADRESSE { get; set; }
        public string VIS_CP { get; set; }
        public string VIS_VILLE { get; set; }
        public Nullable<System.DateTime> VIS_DATEEMBAUCHE { get; set; }
        public string SEC_CODE { get; set; }
        public string LAB_CODE { get; set; }
    
        public virtual LABO LABO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAPPORT_VISITE> RAPPORT_VISITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REALISER> REALISER { get; set; }
        public virtual SECTEUR SECTEUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAVAILLER> TRAVAILLER { get; set; }
    }
}
